# Generated by Django 5.2 on 2025-04-09 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='city',
            field=models.CharField(choices=[('vilnius', 'Vilnius'), ('kaunas', 'Kaunas'), ('klaipeda', 'Klaipėda'), ('siauliai', 'Šiauliai'), ('panevezys', 'Panevėžys')], default='vilnius', max_length=50),
        ),
    ]
