# Generated by Django 5.2 on 2025-04-30 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_game_average_rating_game_complexity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='average_rating',
        ),
        migrations.RemoveField(
            model_name='game',
            name='complexity',
        ),
        migrations.RemoveField(
            model_name='game',
            name='overall_rank',
        ),
        migrations.RemoveField(
            model_name='game',
            name='recommended_age',
        ),
    ]
