# Generated by Django 5.2 on 2025-04-30 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_game_categories_game_language_dependence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='best_player_count',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
