# Generated by Django 5.2 on 2025-04-30 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_game_best_player_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='best_player_count',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
