# Generated by Django 5.2 on 2025-04-30 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_game_best_player_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='best_player_count',
        ),
    ]
