# Generated by Django 5.2 on 2025-05-07 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_game_best_player_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='category',
            field=models.CharField(choices=[('board_games', 'Stalo žaidimai'), ('video_games', 'Video žaidimai'), ('rpg', 'RPG žaidimai'), ('card_games', 'Kortų žaidimai'), ('sports', 'Sporto žaidimai')], default='board_games', max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='repeat_days',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='table_size',
            field=models.CharField(choices=[('S', 'Mažas'), ('M', 'Vidutinis'), ('L', 'Didelis'), ('XL', 'Labai didelis')], default='M', max_length=2),
        ),
        migrations.AlterField(
            model_name='event',
            name='visibility',
            field=models.CharField(choices=[('public', 'Viešas – visi gali prisijungti'), ('protected', 'Apsaugota - reikia leidimo'), ('private', 'Privatus – tik pakviestieji')], default='public', max_length=10),
        ),
    ]
