# Generated by Django 5.2 on 2025-05-07 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_organization_category_alter_event_repeat_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='category',
            field=models.CharField(choices=[('classic_strategic', 'Klasikiniai & Strateginiai'), ('rpg', 'RPG (Role-playing games)'), ('miniature_games', 'Miniatiūrų žaidimai'), ('party_social', 'Vakarėlių ir socialiniai žaidimai'), ('children_games', 'Vaikų žaidimai'), ('educational', 'Edukaciniai žaidimai')], default='classic_strategic', max_length=50),
        ),
    ]
